### ISSUE TITLE
Package Support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-ui#14]
:atom: :package: ❤️ 
This epic tracks issues for support implementations of the most popular Atom packages.
I'm happy for any help and improvement suggestions so please feel free to create a PR or report issues.
## 💬  Community
- [x] <img src="https://avatars1.githubusercontent.com/u/933880" width=16 height=16/>  [`build`](https://atom.io/packages/build) by [noseglid](https://github.com/noseglid) (@arcticicestudio, #3 PR #10 )
- [x] <img src="https://avatars3.githubusercontent.com/u/2833514" width=16 height=16/>  [`color-picker`](https://atom.io/packages/color-picker) by [thomaslindstrom](https://github.com/thomaslindstrom) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars0.githubusercontent.com/u/659763" width=16 height=16/>  [`expose`](https://atom.io/packages/expose) by [mrodalgaard](https://github.com/mrodalgaard) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars3.githubusercontent.com/u/6087523" width=16 height=16/>  [`imdone-atom`](https://atom.io/packages/imdone-atom) by [imdone](https://github.com/imdone) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap`](https://atom.io/packages/minimap) by [atom-minimap](https://github.com/atom-minimap) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap-git-diff`](https://atom.io/packages/minimap-git-diff) by [atom-minimap](https://github.com/atom-minimap) (@arcticicestudio, #16, 8524429a)
- [x] <img src="https://avatars0.githubusercontent.com/u/696872" width=16 height=16/>  [`project-manager`](https://atom.io/packages/project-manager) by [danielbrodin](https://github.com/danielbrodin) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars1.githubusercontent.com/u/836375" width=16 height=16/>  [`script`](https://atom.io/packages/script) by [rgbkrk](https://github.com/rgbkrk) (@arcticicestudio, #3 PR #10)
- [x] <img src="https://avatars3.githubusercontent.com/u/25722" width=16 height=16/>  [`tool-bar`](https://atom.io/packages/tool-bar) by [suda](https://github.com/suda) (@arcticicestudio, #15 , ef2acf66)
## :atom: Core
- [x] [`autocomplete-plus`](https://atom.io/packages/autocomplete-plus) (@arcticicestudio, #3 PR #10)
- [x] [`deprecation-cop`](https://atom.io/packages/deprecation-cop) (@arcticicestudio, #3 PR #10)
- [x] [`markdown-preview`](https://atom.io/packages/markdown-preview) (@arcticicestudio, #3 PR #10)
- [x] [`timecop`](https://atom.io/packages/timecop) (@arcticicestudio, #3 PR #10)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### 💬 Community
  - [x] <img src="https://avatars3.githubusercontent.com/u/7209979" width=16 height=16/>  [`minimap-git-diff`](https://atom.io/packages/minimap-git-diff)
  - [x] <img src="https://avatars3.githubusercontent.com/u/25722" width=16 height=16/>  [`tool-bar`](https://atom.io/packages/tool-bar)

**Comment by arcticicestudio** [comment]
Closing this issue now, special styles for many package are now obsolete since all tasks have been done and the Atom core theme API changed a lot and improved the default behavior on how packages adapt to the enabled theme.

Future optimizations/package supports will be resolved with one issues/language including the associated pull request managed through the [backlog](https://github.com/arcticicestudio/northem-light-atom-ui/projects/1) project board.
