### ISSUE TITLE
Atom 1.13 Shadow DOM removal

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-ui#19]
Starting from Atom version 1.13, the contents of `atom-text-editor` [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html).
This means the `:host` and `::shadow` pseudo-selectors and the `/deep/` combinator selector should be completely removed.
To prevent breakage with existing style sheets, Atom will automatically upgrade selectors for versions less or equal to 1.12.

**Tasks**
  - [x] Remove all `:host` and `::shadow` pseudo-selectors
  - [x] Remove all `/deep/` combinator selectors
  - [x] Update to the new syntax theme package API selector prefix `--syntax-`

**Related issues**: #12

/cc @jaceee @edwardloveall
