### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-ui#3]
A backlog for the [Version 2.0.0](https://github.com/arcticicestudio/northem-light-atom-ui/milestone/1) milestone.
The whole project will be cleaned up and rewritten to adapt the codebase of the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) project.

All sub-issues are listed below and will be merged into the main milestone branch [`release/ghi-#3-2.0.0`](https://github.com/arcticicestudio/northem-light-atom-ui/tree/release/ghi-%233-2.0.0).

  - [x] #4 Nord Atom UI codebase migration
  - [x] #5 Adapt new project setup and documentation style
  - [x] #6 Visually differentiate current tab

**Detailed information about new features can be found in the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui#features) documentations!**

### Color Palette
This major update will migrate to the new Northem Light color palette version [`2.0.0`](https://github.com/arcticicestudio/northem-light/releases/tag/v2.0.0).

### Design
The current design is uncomfortable, unconsistent and has not been updated to the latest Atom version which results in unpredictable bugs and glitch due to changes of the Atom Core.
Northem Light Atom UI will adapt the Nord Atom UI design which provides a clean, elegant and up-to-date UI.

### Package Support
All currently supported packages will be migrated to the new codebase and packages currently supported by Nord Atom UI will be added.

### Documentation
All project documentations will adapt the new project setup and styles and new branding assets will be added.

**Comment by edwardloveall** [comment]
Wonderful! I have some feedback on Nord Atom UI that may help improve this UI theme. I'll list things here but I'm more than happy to put each item in a separate issue or however else you prefer. These are ordered in my opinion from most critical to least.
- Almost no highlighting of the current tab

You state "Optimized tab layout by using the full editor width." as a feature of Nord, which I think is a reasonable goal, but I find it hard to tell which file I'm in by glancing up at the tab bar. This makes it hard for me to A) tell which file I'm currently editing, and therefore B) not know which direction to change tabs to get to a file that I want, and C) not knowing if a file is saved or not.
- Focus color on fields is too bright

The whole theme feel very mellow and understated to me, which I really like. However focusing on any field changed the background color of the field changes from a dark blue to a bright white/very light gray. This breaks that mellow look of the rest of the theme. This also has the side effect of not being able to see placeholder text inside fields.
- Button/Select outlines are too bright

Related to the previous point, it breaks the subdued look of the theme. Also on monitors with a lower pixel density (non-retina) the corners of the outlines look a little disjointed.
- The panels look great, but don't fade out the content in any way

I did some hacking and found that adding a but of a shade between the panels and content unsurprising helps the user focus on them. I think this could be a good addition.

**Comment by arcticicestudio** [comment]
Thanks you for your detailed feedback :+1: 

> - Almost no highlighting of the current tab

I've also noticed this one and already noted down as TODO :smile: 
Currently I'm not sure if I should just add some background-color difference or some kind of left/right/bottom aligned color stripe or something else.

> [...] C) not knowing if a file is saved or not.

There should be a small, light-blue colored circle for unsaved files as shown on the screencast in the features section:
![](https://raw.githubusercontent.com/arcticicestudio/nord-atom-ui/develop/assets/scrcast-feature-tab-dirty-state.gif)
Please let me know if this not the case so I can fix it.

> - Focus color on fields is too bright
> - Button/Select outlines are too bright

The input fields, drop-downs and button outlines are designed to be bright on purpose.
Nord Atom UI- and Syntax are not meant to be pure dark themes but try to give a "north blue" feel and the bright white colors can be compared to :snowflake: snow.
Maybethis could be solved by adding a theme setting to disable bright theme components for a more dark feel?

> [...] This also has the side effect of not being able to see placeholder text inside fields.

This is a know issue and already got reported in [#39](https://github.com/arcticicestudio/nord-atom-ui/issues/39).

> Also on monitors with a lower pixel density (non-retina) the corners of the outlines look a little disjointed.

I don't know if it is possible to avoid this since a `2px` border would look to heavyweight.

> - The panels look great, but don't fade out the content in any way
>   [...] a but of a shade between the panels and content [..]

Also thought about adding more shades for more depth, but I don't want to use it too much to not destroy the flat feel of theme (I don't really like the "Material" design).

Of cource you can go ahead and open some issues for these improvements if you like to, but I'll also note down your improvement suggestions and would create some issues if you don't get the time to :smile: :+1:

**Comment by edwardloveall** [comment]
Added some issues. Good point on the field borders. I thought making the border color more subtle would help but I tried it quickly and it did nothing. Crappy monitors are just crappy ¯_(ツ)_/¯
