### ISSUE TITLE
Nord Atom UI codebase migration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-ui#4]
**Tasks**
  - [x] Adapt core styles codebase
  - [x] Adapt package support styles codebase
  - [x] Implement the theme settings feature
    - [x] Implement the `main.coffee` library
    - [x] Implement `specs`
    - [x] Implement config schema into the `package.json`

This issue is part of the [Version 2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/milestone/1)  milestone tracked in the backlog issue #3.
